export Home from './Home/Home';
export NotFound from './NotFound/NotFound';
export Main from './Main/Main';
export Login from './Login/Login';
export Account from './Account/Account';
export Role from './Role/Role';
export Permissions from './Permissions/Permissions';
export AddRole from './RoleManage/AddRole';
export AddAccount from './AccountManage/AddAccount';
