// 用到的所有action type都放在这里

// Demo
export const INCREMENT = 'INCREMENT';
export const TEST_FETCH_BEGIN = 'TEST_FETCH_BEGIN';
export const TEST_FETCH_SUCC = 'TEST_FETCH_SUCC';
export const TEST_FETCH_FAIL = 'TEST_FETCH_FAIL';
// 登陆
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCC = 'LOGIN_SUCC';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const PERMISSIONS_FETCH_BEGIN = 'PERMISSIONS_FETCH_BEGIN';
export const PERMISSIONS_FETCH_SUCC = 'PERMISSIONS_FETCH_SUCC';
export const PERMISSIONS_FETCH_FAIL = 'PERMISSIONS_FETCH_FAIL';

export const ROLE_FETCH_BEGIN = 'ROLE_FETCH_BEGIN';
export const ROLE_FETCH_SUCC = 'ROLE_FETCH_SUCC';
export const ROLE_FETCH_FAIL = 'ROLE_FETCH_FAIL';

export const SEARCH_ROLE_TEXT = 'SEARCH_ROLE_TEXT';

export const ACCOUNT_FETCH_BEGIN = 'ACCOUNT_FETCH_BEGIN';
export const ACCOUNT_FETCH_SUCC = 'ACCOUNT_FETCH_SUCC';
export const ACCOUNT_FETCH_FAIL = 'ACCOUNT_FETCH_FAIL';

export const SEARCH_ACCOUNT_TEXT = 'SEARCH_ACCOUNT_TEXT';
export const SEARCH_NAME_TEXT = 'SEARCH_NAME_TEXT';

export const SEARCH_ACCOUNT_BEGIN = 'SEARCH_ACCOUNT_BEGIN';
export const SEARCH_ACCOUNT_SUCC = 'SEARCH_ACCOUNT_SUCC';
export const SEARCH_ACCOUNT_FAIL = 'SEARCH_ACCOUNT_FAIL';

export const SEARCH_NAME_BEGIN = 'SEARCH_NAME_BEGIN';
export const SEARCH_NAME_SUCC = 'SEARCH_NAME_SUCC';
export const SEARCH_NAME_FAIL = 'SEARCH_NAME_FAIL';
