// 用到的所有action type都放在这里

// export const _BEGIN = '_BEGIN';
// export const _SUCC = '_SUCC';
// export const _FAIL = '_FAIL';
// Demo
export const INCREMENT = 'INCREMENT';
export const TEST_FETCH_BEGIN = 'TEST_FETCH_BEGIN';
export const TEST_FETCH_SUCC = 'TEST_FETCH_SUCC';
export const TEST_FETCH_FAIL = 'TEST_FETCH_FAIL';
// 登陆
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCC = 'LOGIN_SUCC';
export const LOGIN_FAIL = 'LOGIN_FAIL';
// 权限列表
export const PERMISSIONS_FETCH_BEGIN = 'PERMISSIONS_FETCH_BEGIN';
export const PERMISSIONS_FETCH_SUCC = 'PERMISSIONS_FETCH_SUCC';
export const PERMISSIONS_FETCH_FAIL = 'PERMISSIONS_FETCH_FAIL';
// 角色列表
export const ROLE_FETCH_BEGIN = 'ROLE_FETCH_BEGIN';
export const ROLE_FETCH_SUCC = 'ROLE_FETCH_SUCC';
export const ROLE_FETCH_FAIL = 'ROLE_FETCH_FAIL';
// 角色搜索
export const SEARCH_ROLE_TEXT = 'SEARCH_ROLE_TEXT';
// 账号列表
export const ACCOUNT_FETCH_BEGIN = 'ACCOUNT_FETCH_BEGIN';
export const ACCOUNT_FETCH_SUCC = 'ACCOUNT_FETCH_SUCC';
export const ACCOUNT_FETCH_FAIL = 'ACCOUNT_FETCH_FAIL';
// 账号搜索、名字搜索
export const SEARCH_ACCOUNT_TEXT = 'SEARCH_ACCOUNT_TEXT';
export const SEARCH_NAME_TEXT = 'SEARCH_NAME_TEXT';

export const SEARCH_ACCOUNT_BEGIN = 'SEARCH_ACCOUNT_BEGIN';
export const SEARCH_ACCOUNT_SUCC = 'SEARCH_ACCOUNT_SUCC';
export const SEARCH_ACCOUNT_FAIL = 'SEARCH_ACCOUNT_FAIL';

export const SEARCH_NAME_BEGIN = 'SEARCH_NAME_BEGIN';
export const SEARCH_NAME_SUCC = 'SEARCH_NAME_SUCC';
export const SEARCH_NAME_FAIL = 'SEARCH_NAME_FAIL';
// 修改密码
export const CHANGE_PWD_BEGIN = 'CHANGE_PWD_BEGIN';
export const CHANGE_PWD_SUCC = 'CHANGE_PWD_SUCC';
export const CHANGE_PWD_FAIL = 'CHANGE_PWD_FAIL';

// 添加账号
export const ACCOUNT_ADD_BEGIN = 'ACCOUNT_ADD_BEGIN';
export const ACCOUNT_ADD_SUCC = 'ACCOUNT_ADD_SUCC';
export const ACCOUNT_ADD_FAIL = 'ACCOUNT_ADD_FAIL';

// 获取角色列表
export const ROLELIST_GET_BEGIN = 'ROLELIST_GET_BEGIN';
export const ROLELIST_GET_SUCC = 'ROLELIST_GET_SUCC';
export const ROLELIST_GET_FAIL = 'ROLELIST_GET_FAIL';

// 编辑账号
export const ACCOUNT_EDIT_BEGIN = 'ACCOUNT_EDIT_BEGIN';
export const ACCOUNT_EDIT_SUCC = 'ACCOUNT_EDIT_SUCC';
export const ACCOUNT_EDIT_FAIL = 'ACCOUNT_EDIT_FAIL';

// 权限列表
export const JURISDICTIONLIST_GET_BEGIN = 'JURISDICTIONLIST_GET_BEGIN';
export const JURISDICTIONLIST_GET_SUCC = 'JURISDICTIONLIST_GET_SUCC';
export const JURISDICTIONLIST_GET_FAIL = 'JURISDICTIONLIST_GET_FAIL';

// 编辑角色权限
export const EDITROLEJURISDICTION_GET_BEGIN = 'EDITROLEJURISDICTION_GET_BEGIN';
export const EDITROLEJURISDICTION_GET_SUCC = 'EDITROLEJURISDICTION_GET_SUCC';
export const EDITROLEJURISDICTION_GET_FAIL = 'EDITROLEJURISDICTION_GET_FAIL';
